In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets, svm, metrics

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()
train = digits.data
targets = digits.target

In [4]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, init = 'k-means++', random_state = 0)
pred = kmeans.fit(train)

In [5]:
# print(targets)
Labels = pred.labels_
print(Labels)

[5 7 7 ... 7 3 3]


In [6]:
def clusterChecking(tar,lab):
    new_lab=np.copy(lab)
    for j in range(10):
        temp=np.where(lab==j)
        temp_array=tar[temp]
        vals,counts = np.unique(temp_array, return_counts=True)
       
        index = np.argmax(counts)
        m=vals[index]
        new_lab[temp]=m
    return new_lab  

In [7]:
new = clusterChecking(targets, Labels)
print(targets)
# print(Labels)
print(new)

[0 1 2 ... 8 9 8]
[0 8 8 ... 8 9 9]


In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(targets, new)
print(cm)

[[177   0   0   0   1   0   0   0   0   0]
 [  0  55  24   1   0   1   2   0  99   0]
 [  1   2 148  13   0   0   0   3   8   2]
 [  0   0   0 154   0   2   0   7   7  13]
 [  0   7   0   0 163   0   0   7   4   0]
 [  0   0   0   0   2 136   1   0   0  43]
 [  1   1   0   0   0   0 177   0   2   0]
 [  0   0   0   0   0   0   0 177   2   0]
 [  0   5   3   2   0   4   2   5 100  53]
 [  0  20   0   6   0   6   0   7   2 139]]


In [9]:
accuracy = metrics.fowlkes_mallows_score(targets, new)
print('Accuracy: ',accuracy*100, '%')

Accuracy:  70.2734687012768 %
